---
title: "Maximum Likelihood & Delta Method"
runtime: shiny
output: html_document
---

# Maximum Likelihood

## Binomial Distribution

```{r binom, echo = FALSE}
inputPanel(
  sliderInput("n.bi", label = "Sample Size (n)",
              min = 1, max = 500, value = 10, step = 1),
  
  sliderInput("p.bi", label = "True Parameter (p)",
              min = 0, max = 1, value = .5, step = .01)
)

renderPlot({
  hist(rbinom(input$n.bi, size = 30, prob = input$p.bi), col = "darkgreen",
       breaks = 0:30, freq = FALSE, ylim = c(0, 1), las = 1L, xlab = "X",
       main = "Observed Distribution Changes with Underlying Parameter")
})
```

## Normal Distribution

```{r norm, echo = FALSE}
inputPanel(
  sliderInput("n.nr", label = "Sample Size (n)",
              min = 1, max = 500, value = 10, step = 1),
  
  sliderInput("u.nr", label = "True Mean (mu)",
              min = 0, max = 10, value = 5, step = .2),
  
  sliderInput("s.nr", label = "True Std. Dev (sigma)",
              min = 0, max = 3, value = 1, step = .1)
)

renderPlot({
  hist(rnorm(input$n.nr, mean = input$u.nr, sd = input$s.nr), 
       col = "darkgreen", xlab = "X", las = 1L,
       breaks = -10:20, freq = FALSE, ylim = c(0, 1), 
       main = "Observed Distribution Changes with Underlying Parameter")
})
```
